[[customizations.user]]
name = "test"
password = "testtest"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDFGdN6jCcvNSbV4zXF8qLtE7yES+BPwdJydHYpewd/GNGUhGumCz4OOn9xs7m7/BMRxzeyUJCn7zlSw4RZn2iCw9kmVS6YILyWxsQlVD5Uq5683yRRqcjcsNIWlf6LePHgqguGAIaoTMlJBsNxzZvLU50Nonwa1Ug5D3RdJT7MxFaiHMBcCS8W6UTHxX76Euph7WjS/fRKM7ubp8VHfDG80IZy7ymULZrtOZp9aK3ugLC6AQFE3Y/Xntqye8QiS7FsUF4stefFLKrBpVRhtXVzdp8ZYX4L9+4deTUp2B7R6L0TcG8VSlebJR53KxKx0OZlqbIlv7BR/vgPDycFsLOgq0ztms8AgDqOb2agENvuWnsoqA/PG0ETQ6KxlyCFgu19vPFLVb61LsKbFTmMucBdE2LhuO38q1TeKBKnTXJJ9P1CAMTVMn4KtFk98fUOf7y2ojKCOy0/wt3UU6QZ3QsKHcTQuy3ZX/8FJzJQ0TZWvqVBkBUs+Y8wWIoyZDQ5tQuIDtKw6oqKp4Vech9M02/srQQ/uOzF7xjZQ13WtlwqQtkC0Ydpf520IVZ3w+V4CdaoJTx4sgbwY7p0dl4CnVVkttVC9p+Liwb4mxzKtvY2NGoKUMbqU5FzPalw0SqttxRCDD0dEuZHdml2i+qWRF80tblbYXfApLo/ClNLmp1TlQ=="
groups = ["wheel"]

