# ref: https://github.com/yureutaejin/yob/blob/main/.github/workflows/_convert-to-disk.yaml

name: "Convert OCI Container to Disk Image"
run-name: "Convert OCI Container to Disk Image - ${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      oci_registry:
        description: 'Choose the OCI registry you want to use'
        required: true
        options:
          - quay.io
          - docker.io
        default: 'quay.io'
        type: choice
      oci_image_repo:
        description: 'Type the image repository path in OCI registry you want to push (`{tenancy-namespace}/{repo-name}`)'
        required: true
        default: 'beengineer/bgnr-fedora-bootc-42'
        type: string
      oci_image_tag:
        description: 'Type the image tag you want to use'
        required: true
        default: '1.0-20251002'
        type: string
      target_interface:
        description: 'Type the target interface you want to build (e.g. `core`, `desktop`, `all`)'
        required: true
        default: 'all'
        type: string
      default_disk:
        description: 'Type disk name you want to use as rootfs (e.g. `sda`, `nvme0n1`)'
        required: true
        default: 'sda'
        type: string
      disk_format:
        description: 'Choose disk format you want to convert the OCI image into'
        required: true
        options:
          - anaconda-iso
          - ami
        default: 'anaconda-iso'
        type: choice
      rootfs:
        description: 'Choose root filesystem you want to use'
        required: true
        options:
          - btrfs
          - exr4
          - xfs
        default: 'btrfs'
        type: choice
      aws_s3_bucket:
        description: '(Only for `ami` disk format) Type the AWS S3 bucket name you want to use'
        required: false
        default: 'none'
        type: string

jobs:
  convert-to-disk-image:
    run-on:
      label: bootc-builder

    steps:
      - name: Verify prerequisites
        run: |
          make --version &> /dev/null || { echo "Make is not installed"; exit 1; }
          docker --version &> /dev/null || { echo "Docker is not installed"; exit 1; }
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to OCI registry
        run: |
          make login-public-oci-registry
        env:
          OCI_REGISTRY: ${{ inputs.oci_registry }}
          OCI_REGISTRY_USERNAME : ${{ secrets.OCI_REGISTRY_BOT_USERNAME }}
          OCI_REGISTRY_PASSWORD : ${{ secrets.OCI_REGISTRY_BOT_PASSWORD }}

      - name: Congfigure AWS credentials
        if: ${{ inputs.disk_format == 'ami' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Pull bootc image from OCI registry
        run: |
          echo "::group::Pull bootc image from OCI registry"
          make pull-bootc
          echo ":;endgroup::"
        env:
          OCI_REGISTRY: ${{ inputs.oci_registry }}
          OCI_IMAGE_REPO: ${{ inputs.oci_image_repo }}
          OCI_IMAGE_TAG: ${{ inputs.oci_image_tag }}
          TARGET_INTERFACE: ${{ inputs.target_interface }}
      
      - name: Save Image as tgz
        run: |
          echo "::group::Save image as tgz"
          make save-image-as-tgz
          echo "::endgroup::"
        env:
          OCI_REGISTRY: ${{ inputs.oci_registry }}
          OCI_IMAGE_REPO: ${{ inputs.oci_image_repo }}
          OCI_IMAGE_TAG: ${{ inputs.oci_image_tag }}
          TARGET_INTERFACE: ${{ inputs.target_interface }}

      - name: Convert OCI image into specified disk format
        run: |
          echo "::group::Convert OCI Image into specified disk format:"
          make convert-to-${DISK_FORMAT}
          echo "::endgroup::"
        env:
          OCI_REGISTRY: ${{ inputs.oci_registry }}
          OCI_IMAGE_REPO: ${{ inputs.oci_image_repo }}
          OCI_IMAGE_TAG: ${{ inputs.oci_image_tag }}
          TARGET_INTERFACE: ${{ inputs.target_interface }}
          DISK_FORMAT: ${{ inputs.disk_format }}
          DEFAULT_DISK: ${{ inputs.disk_format }}
          ROOTFS: ${{ inputs.rootfs }}
          AWS_S3_BUCKET: ${{ vars.aws_s3_bucket }}
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
      
      - name: Save iso format image
        if: ${{ inputs.disk_format == 'iso'}}
        run: |
          sudo chown -R $USER:$USER ./image-builder-output
          sudo mkdir -p /opt/bootc-os-disk-images/${{ github.run_number }}
          sudo mv image-builder-output /opt/bootc-os-disk-images/${{ github.run_number }}
          sudo rm -rf ./image-builder-output
        env:
          OCI_REGISTRY: ${{ inputs.oci_registry }}
          OCI_IMAGE_REPO: ${{ inputs.oci_image_repo }}
          OCI_IMAGE_TAG: ${{ inputs.oci_image_tag }}
          TARGET_INTERFACE: ${{ inputs.target_interface }}